name: "Zenodo Release Action"
description: "Release zenodo metadata so you don't have to give admin hook access"
inputs:
  archive:
    description: the path to the release archive
    required: true
  token:
    description: zenodo token
    required: true
  version:
    description: the release version
    required: true
  zenodo_json:
    description: Path to zenodo.json to upload with metadata (must exist)
  doi:
    descripton: The DOI to create a new version from
  body:
    descripton: The release description.
  html_url:
    descripton: The url to the release
    
outputs:
  badge:
    description: badge url
    value: ${{ steps.deploy.outputs.badge }}
  bucket:
    description: bucket url
    value: ${{ steps.deploy.outputs.bucket }}
  conceptbadge:
    description: concept badge url
    value: ${{ steps.deploy.outputs.conceptbadge }}
  conceptdoi:
    description: concept doi url
    value: ${{ steps.deploy.outputs.conceptdoi }}
  doi:
    description: doi url
    value: ${{ steps.deploy.outputs.doi }}
  latest:
    description: latest url
    value: ${{ steps.deploy.outputs.latest }}
  latest_html:
    description: latest html url
    value: ${{ steps.deploy.outputs.latest_html }}
  record:
    description: record url
    value: ${{ steps.deploy.outputs.record }}
  record_html:
    description: record html url
    value: ${{ steps.deploy.outputs.record_html }}

runs:
  using: "composite"
  steps:
- uses: actions/checkout@v3
    - name: download archive to runner
      env:
        zipball: ${{ github.event.release.zipball_url }}
      run: |
        name=$(basename ${zipball})        
        curl -L $zipball > $name
        echo "archive=${name}" >> $GITHUB_ENV

    - name: Run Zenodo Deploy
      uses: nmfs-opensci/zenodo-release@main
      with:
        token: ${{ secrets.ZENODO_TOKEN }}
        version: ${{ github.event.release.tag_name }}
        zenodo_json: .zenodo.json   # optional if adding to an existing record in Zenodo
        archive: ${{ env.archive }}
    - name: Deploy Zenodo
      id: deploy
      env:
        zenodo_json: ${{ inputs.zenodo_json }}
        archive: ${{ inputs.archive }}
        version: ${{ github.event.release.tag_name }}
        ACTION_PATH: ${{ github.action_path }}
        ZENODO_TOKEN: ${{ inputs.token }}
        doi: ${{ inputs.doi }}
        body: test
        html_url: ${{ github.event.release.html_url }}
      run: |
        pip install markdown
        command="python ${{ github.action_path }}/scripts/deploy.py upload ${archive} --version ${version} --html-url ${html_url} --body ${body}"
        if [[ "${doi}" != "" ]]; then
            command="$command --doi ${doi}"
        fi
        if [[ "${zenodo_json}" != "" ]]; then
            command="$command --zenodo-json ${zenodo_json}"
        fi
        echo '${{ github.event.release.body }}' > body.txt
        printf "$command\n"
        $command

      shell: bash
